# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [96]:
import numpy as np

#### 2. Print your NumPy version.

In [97]:
np.version

<module 'numpy.version' from 'C:\\Users\\Shinemet\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [98]:
a = np.random.random((2, 3, 5))

In [99]:
np.random.rand(2, 3, 5)

array([[[0.08531957, 0.73334079, 0.26274373, 0.53571971, 0.06814764],
        [0.17175014, 0.55174522, 0.73728917, 0.69216647, 0.84301663],
        [0.37587191, 0.81963839, 0.00890718, 0.85994475, 0.75911419]],

       [[0.23280741, 0.97723492, 0.52788517, 0.57878078, 0.41915797],
        [0.49694988, 0.88722581, 0.42896389, 0.41240984, 0.207778  ],
        [0.11003976, 0.12711582, 0.95288696, 0.84164869, 0.75163515]]])

In [100]:
np.random.default_rng(1).random((2, 3, 5))

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

#### 4. Print *a*.


In [101]:
a

array([[[0.51671014, 0.49015418, 0.07626415, 0.05800046, 0.83340577],
        [0.73930466, 0.0730032 , 0.88788472, 0.0195973 , 0.78885851],
        [0.89879215, 0.2833878 , 0.70390365, 0.96515772, 0.68790475]],

       [[0.88368058, 0.17907791, 0.93946567, 0.60805328, 0.87248123],
        [0.22329691, 0.26529922, 0.11781177, 0.6523394 , 0.67438976],
        [0.46924561, 0.36951907, 0.04213817, 0.6390918 , 0.43138973]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [102]:
b = np.ones((5, 2, 3), dtype=int)

#### 6. Print *b*.


In [103]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [104]:
# No
print(a.shape)
print(b.shape)
print(a.shape==b.shape)

(2, 3, 5)
(5, 2, 3)
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [105]:
# No, it is possible since the 2 arrays do not have the same size:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [106]:
c = b.reshape(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [107]:
# Now the 2 arrays have the same size (2, 3, 5)
d = a + c
d

array([[[1.51671014, 1.49015418, 1.07626415, 1.05800046, 1.83340577],
        [1.73930466, 1.0730032 , 1.88788472, 1.0195973 , 1.78885851],
        [1.89879215, 1.2833878 , 1.70390365, 1.96515772, 1.68790475]],

       [[1.88368058, 1.17907791, 1.93946567, 1.60805328, 1.87248123],
        [1.22329691, 1.26529922, 1.11781177, 1.6523394 , 1.67438976],
        [1.46924561, 1.36951907, 1.04213817, 1.6390918 , 1.43138973]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [108]:
# The difference between each value of both arrays is 1 because d = a + c where all the values of c = all the values of b = 1
print(a)
print('\n')
print(d)

[[[0.51671014 0.49015418 0.07626415 0.05800046 0.83340577]
  [0.73930466 0.0730032  0.88788472 0.0195973  0.78885851]
  [0.89879215 0.2833878  0.70390365 0.96515772 0.68790475]]

 [[0.88368058 0.17907791 0.93946567 0.60805328 0.87248123]
  [0.22329691 0.26529922 0.11781177 0.6523394  0.67438976]
  [0.46924561 0.36951907 0.04213817 0.6390918  0.43138973]]]


[[[1.51671014 1.49015418 1.07626415 1.05800046 1.83340577]
  [1.73930466 1.0730032  1.88788472 1.0195973  1.78885851]
  [1.89879215 1.2833878  1.70390365 1.96515772 1.68790475]]

 [[1.88368058 1.17907791 1.93946567 1.60805328 1.87248123]
  [1.22329691 1.26529922 1.11781177 1.6523394  1.67438976]
  [1.46924561 1.36951907 1.04213817 1.6390918  1.43138973]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [109]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [110]:
# e = a because e = a * c where all the values of c = 1
print(a)
print('\n')
print(e)

[[[0.51671014 0.49015418 0.07626415 0.05800046 0.83340577]
  [0.73930466 0.0730032  0.88788472 0.0195973  0.78885851]
  [0.89879215 0.2833878  0.70390365 0.96515772 0.68790475]]

 [[0.88368058 0.17907791 0.93946567 0.60805328 0.87248123]
  [0.22329691 0.26529922 0.11781177 0.6523394  0.67438976]
  [0.46924561 0.36951907 0.04213817 0.6390918  0.43138973]]]


[[[0.51671014 0.49015418 0.07626415 0.05800046 0.83340577]
  [0.73930466 0.0730032  0.88788472 0.0195973  0.78885851]
  [0.89879215 0.2833878  0.70390365 0.96515772 0.68790475]]

 [[0.88368058 0.17907791 0.93946567 0.60805328 0.87248123]
  [0.22329691 0.26529922 0.11781177 0.6523394  0.67438976]
  [0.46924561 0.36951907 0.04213817 0.6390918  0.43138973]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [111]:
d_max = np.amax(d)
d_min = np.amin(d)
print(d_max, d_min)

1.9651577242854272 1.019597300574965


In [112]:
d_mean = np.mean(d)
d_mean

1.5129869759177212

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [113]:
f = np.empty((2, 3, 5))
f

array([[[0.51671014, 0.49015418, 0.07626415, 0.05800046, 0.83340577],
        [0.73930466, 0.0730032 , 0.88788472, 0.0195973 , 0.78885851],
        [0.89879215, 0.2833878 , 0.70390365, 0.96515772, 0.68790475]],

       [[0.88368058, 0.17907791, 0.93946567, 0.60805328, 0.87248123],
        [0.22329691, 0.26529922, 0.11781177, 0.6523394 , 0.67438976],
        [0.46924561, 0.36951907, 0.04213817, 0.6390918 , 0.43138973]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [114]:
d

array([[[1.51671014, 1.49015418, 1.07626415, 1.05800046, 1.83340577],
        [1.73930466, 1.0730032 , 1.88788472, 1.0195973 , 1.78885851],
        [1.89879215, 1.2833878 , 1.70390365, 1.96515772, 1.68790475]],

       [[1.88368058, 1.17907791, 1.93946567, 1.60805328, 1.87248123],
        [1.22329691, 1.26529922, 1.11781177, 1.6523394 , 1.67438976],
        [1.46924561, 1.36951907, 1.04213817, 1.6390918 , 1.43138973]]])

In [115]:
for x in range(2):
    for y in range(3):
        for z in range(5):
            if d_min < d[x][y][z] < d_mean:
                f[x][y][z] = 25
            elif d_mean < d[x][y][z] < d_max:
                f[x][y][z] = 75
            elif d[x][y][z] == d_mean:
                f[x][y][z] = 50
            elif d[x][y][z] == d_min: 
                f[x][y][z] = 0
            else: 
                f[x][y][z] = 100

f

array([[[ 75.,  25.,  25.,  25.,  75.],
        [ 75.,  25.,  75.,   0.,  75.],
        [ 75.,  25.,  75., 100.,  75.]],

       [[ 75.,  25.,  75.,  75.,  75.],
        [ 25.,  25.,  25.,  75.,  75.],
        [ 25.,  25.,  25.,  75.,  25.]]])

In [116]:
# Another way to seed f called f2:
f2 = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        f2 += [25]
    if d_mean < x < d_max:
        f2 += [75]
    if x == d_mean:
        f2 += [50]
    if x == d_min:
        f2 += [0]
    if x == d_max:
        f2 += [100]
        
f2 = np.reshape(f2, d.shape)
print(f2)

[[[ 75  25  25  25  75]
  [ 75  25  75   0  75]
  [ 75  25  75 100  75]]

 [[ 75  25  75  75  75]
  [ 25  25  25  75  75]
  [ 25  25  25  75  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [117]:
print(d,'\n\n',f)

[[[1.51671014 1.49015418 1.07626415 1.05800046 1.83340577]
  [1.73930466 1.0730032  1.88788472 1.0195973  1.78885851]
  [1.89879215 1.2833878  1.70390365 1.96515772 1.68790475]]

 [[1.88368058 1.17907791 1.93946567 1.60805328 1.87248123]
  [1.22329691 1.26529922 1.11781177 1.6523394  1.67438976]
  [1.46924561 1.36951907 1.04213817 1.6390918  1.43138973]]] 

 [[[ 75.  25.  25.  25.  75.]
  [ 75.  25.  75.   0.  75.]
  [ 75.  25.  75. 100.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [118]:
g = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        g += 'A'
    if d_mean < x < d_max:
        g += 'B'
    if x == d_mean:
        g += 'C'
    if x == d_min:
        g += 'D'
    if x == d_max:
        g += 'E'
        
g = np.reshape(g, d.shape)
print(g)

[[['B' 'A' 'A' 'A' 'B']
  ['B' 'A' 'B' 'D' 'B']
  ['B' 'A' 'B' 'E' 'B']]

 [['B' 'A' 'B' 'B' 'B']
  ['A' 'A' 'A' 'B' 'B']
  ['A' 'A' 'A' 'B' 'A']]]
